- odd-platform-ui/src/components/DataEntityDetails/Lineage/Lineage.tsx
- odd-platform-ui/src/components/shared/AppGraph/AppGraph.tsx
- odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNode.tsx
- Fixed padding when switching between full and compact modes.
- Added empty node compact view placeholder.
- Set max zoom to 1.
> Improvements to lineage

- odd-platform-ui/src/components/Overview/DataEntityList/DataEntityList.tsx
- odd-platform-ui/src/components/Overview/DataEntityList/DataEntityListStyles.ts
- odd-platform-ui/src/components/shared/AppTabs/AppTabs.tsx
- odd-platform-ui/src/components/shared/AppToolbar/AppToolbar.tsx
- Fixed entity type labels identation on home page.
- Fixed tabs in toolbar.
- Moved Management link to toolbar tabs.
> Fixed entity type labels identation, tabs in toolbar.

- odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsStyles.ts
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewTransformerStats/OverviewTransformerStatsStyles.ts
- odd-platform-ui/src/components/Search/Filters/Filters.tsx
- odd-platform-ui/src/components/Search/Filters/FiltersContainer.tsx
- odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
- odd-platform-ui/src/components/Search/Results/Results.tsx
- odd-platform-ui/src/components/Search/Results/ResultsContainer.tsx
- odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNode.tsx
- odd-platform-ui/src/redux/interfaces/graph.ts
- odd-platform-ui/src/redux/interfaces/search.ts
- odd-platform-ui/src/redux/selectors/dataentitySearch.selectors.ts
- Fixed search type retrieval.
- Updated lineage node details link.
- Fixed lineage height.
> Bugfix misc

- odd-platform-api/src/main/java/com/provectus/oddplatform/repository/AbstractSoftDeleteCRUDRepository.java
- odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepositoryImpl.java
- odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataSourceRepositoryImpl.java
> Fix soft delete in facet search API and management

- odd-platform-ui/src/components/Alerts/Alerts.tsx
- odd-platform-ui/src/components/Alerts/AlertsContainer.tsx
- odd-platform-ui/src/components/Alerts/AlertsList/AlertListSkeleton/AlertListSkeleton.tsx
- odd-platform-ui/src/components/Alerts/AlertsList/AlertListSkeleton/AlertListSkeletonStyles.ts
- odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx
- odd-platform-ui/src/components/Alerts/AlertsList/AlertsListContainer.tsx
- odd-platform-ui/src/components/Overview/Overview.tsx
- odd-platform-ui/src/components/Overview/OverviewContainer.tsx
- odd-platform-ui/src/components/shared/EmptyContentPlaceholder/EmptyContentPlaceholder.tsx
- odd-platform-ui/src/components/shared/EmptyContentPlaceholder/EmptyContentPlaceholderStyles.ts
- odd-platform-ui/src/components/shared/Icons/EmptyIcon.tsx
- odd-platform-ui/src/lib/paths.ts
- odd-platform-ui/src/redux/actions/alert.actions.ts
- odd-platform-ui/src/redux/reducers/alerts.reducer.ts
- Integrated alerts widget
- Added pagination and loading state to alerts list
> Home Page: Alerts widget

- odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepositoryImpl.java
> Enable FTS prefix matching

- odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepositoryImpl.java
- odd-platform-api/src/main/java/com/provectus/oddplatform/repository/util/JooqRecordHelper.java
- odd-platform-api/src/main/java/com/provectus/oddplatform/service/IngestionServiceImpl.java
> Rework JOOQ mappers to get rid of ambiguous matches

- .github/workflows/build.yaml
- .github/workflows/release-build.yaml
- odd-platform-ui/build.gradle
- odd-platform-ui/package.json
> Fix CI build issue

- odd-platform-ui/src/components/Search/Results/Results.tsx
> BugFix: when go to the catalog page, old search results are shown

- config/checkstyle/checkstyle.xml
- odd-platform-api/src/main/java/com/provectus/oddplatform/service/IngestionServiceImpl.java
The only change in the xml file:
> Finals validation for checkstyle

- odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
- odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
- odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItem.tsx
- odd-platform-ui/src/components/Search/Results/Results.tsx
- odd-platform-ui/src/redux/interfaces/dataQualityTest.ts
- odd-platform-ui/src/redux/reducers/dataQualityTest.reducer.ts
Fixed bug with counting broken test runs.
Added right search results table header for Data Quality entity.
> BugFix: "broken" test runs count

- odd-platform-ui/src/components/shared/AppGraph/AppGraph.tsx
- odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNode.tsx
- odd-platform-ui/src/components/shared/AppGraph/AppGraphStyles.ts
Fixed Safari bug with wrong render of lineage.
> BugFix: Lineage in Safari

- odd-platform-api/src/main/java/com/provectus/oddplatform/repository/DataEntityRepositoryImpl.java
> Search API: Take facets conditions into account when the query is present

- odd-platform-api/build.gradle
- odd-platform-api/gradle.properties
- odd-platform-api/src/main/java/com/provectus/oddplatform/config/ResourceProviderWebFilter.java
- odd-platform-api/src/main/resources/application.yml
> Prometheus metrics export

- .github/workflows/codestyle.yaml
> Make checkstyle build application

- odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
- odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreview.tsx
- odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreviewStyles.ts
Added ability to see formatted text in entity preview
Resolve #261
> Bugfix: Preview icon styles fix.

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
> Structure TSVector is not being calculated if field doesn't contain labels

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/IngestionMapperImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LineageRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LineageRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
- odd-platform-api/src/main/resources/db/migration/V0_0_17__add_establisher_into_lineage.sql
> Drop dependencies from lineage table in Ingestion API

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetVersionRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LabelRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LabelRepositoryImpl.java
> Delete label relations after label deleted

- odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
Now in editing datasource user can't change type of adapter (url or oddrn)
Resolve #298
> Bugfix: Fixed bug with simultaneous oddrn and connectionUrl in payload.

- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewDataConsumerStats/OverviewDataConsumerStats.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewDataInputStats/OverviewDataInputStats.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewStats.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewTransformerStats/OverviewTransformerStats.tsx
- odd-platform-ui/src/components/Search/Results/Results.tsx
- odd-platform-ui/src/components/shared/DialogWrapper/DialogWrapper.tsx
- odd-platform-ui/src/components/shared/DialogWrapper/DialogWrapperStyles.ts
- odd-platform-ui/src/components/shared/EntitiesListModal/EntitiesListModal.tsx
- odd-platform-ui/src/components/shared/EntitiesListModal/EntitiesListModalStyles.ts
Fixed bug with search tabs.
Resolved #306
> Implemented EntitiesListModal component.

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/IngestionMapperImpl.java
> Fix duplicate fetching and ingestion of specific attributes

- odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
> Bugfix: Datasource form validation.

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/DataEntityDimensionsDto.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetFieldRepositoryImpl.java
> Dataset Field update doesn't update TSVectors

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
> Fix NPE in Ingestion API

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImpl.java
> Fix alerts totals

- odd-platform-ui/src/components/shared/AppGraph/AppGraph.tsx
- odd-platform-ui/src/components/shared/AppGraph/AppGraphCrossLink/AppGraphCrossLink.tsx
- odd-platform-ui/src/components/shared/AppGraph/AppGraphCrossLink/AppGraphCrossLinkStyles.ts
- odd-platform-ui/src/components/shared/TestRunStatusIcon/TestRunStatusIconStyles.ts
- odd-platform-ui/src/redux/interfaces/dataentityLineage.ts
- odd-platform-ui/src/redux/reducers/dataentityLineage.reducer.ts
> Implemented cross links visualization.

- odd-platform-ui/src/redux/reducers/dataentityLineage.reducer.ts
> Fixed bug with updating local lineage state

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqFTSHelper.java
> Remove CD ranking out of FTS

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqFTSHelper.java
> FTS partial matches

- odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/GroupedEntitiesListModal/GroupedEntitiesListModal.tsx
- odd-platform-ui/src/redux/reducers/dataentityLineage.reducer.ts
> Bugfix: lineage updating

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
- odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
- odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemStyles.ts
- odd-platform-ui/src/components/Search/Results/Results.tsx
- odd-platform-ui/src/components/shared/AppButton/AppButton.tsx
- odd-platform-ui/src/components/shared/AppIconButton/AppIconButton.tsx
- odd-platform-ui/src/components/shared/AppIconButton/AppIconButtonStyles.ts
- odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCell.tsx
- odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCellMenu/TruncatedCellMenu.tsx
- odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCellMenu/TruncatedCellMenuStyles.ts
- odd-platform-ui/src/components/shared/TruncatedCell/TruncatedCellStyles.ts
- odd-platform-ui/src/theme/interfaces.ts
- odd-platform-ui/src/theme/palette.ts
> Enhancement: Specific attributes for entities at results page

- odd-platform-ui/src/components/shared/AppGraph/AppGraphLink/AppGraphLink.tsx
- odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNode.tsx
- odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNodeStyles.ts
**What changes did you make?** 
Refactored AppGraphNode to styled components.
Resolve #374
> Refactored AppGraphNode to styled components.

- odd-platform-api/src/main/resources/application.yml
**What changes did you make?** 
Disabled LDAP healthcheck by default
> disable ldap healthcheck by defalut

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AbstractCRUDRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
> Bug: Ingestion API doesn't take hollow entities into the account while persisting Data Entities 

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqFTSHelper.java
> Replace spaces with conjunction in FTS query

- odd-platform-api/src/main/resources/db/migration/V0_0_26__remove_length_constraints.sql
> Remove length constraint

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/EnumValueMapperImpl.java
> trim enums name/description

- odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldEnumsEditForm/DatasetFieldEnumsFormItem/DatasetFieldEnumsFormItem.tsx
Fixed bug with deleted enum values.
Resolve #406
> Bugfix: deleted enum values are appearing in new tabs.

- odd-platform-ui/src/components/Alerts/Alerts.tsx
- odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx
- odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
Alert status updating on Alerts page fixed
Resolve #402 
> alert status works correcttly

- .github/dependabot.yml
Set configuration options to automatically package updates by minor versions.
Resolve #366
> Implemented dependabot.yaml

- .github/dependabot.yml
Changed dependabot.yml file version according to the docs
> Changed dependabot version

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertLocatorImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertServiceImpl.java
> fetch has alerts info

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataQualityRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqQueryHelper.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/DataQualityRepositoryImplTest.java
Fix for https://github.com/opendatadiscovery/odd-platform/issues/443
Sort data entity task run history in desc order
> sort task runs in desc order

- odd-platform-ui/src/components/Overview/Overview.tsx
- odd-platform-ui/src/components/Overview/OverviewStyles.ts
In the Overview page added paddings for a block with the list.
**How Has This Been Tested?**
**Checklist**
> added paddings for every overview list

- .github/workflows/release-build.yaml
> Update latest tag of GHCR image after release

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/NamespaceRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/NamespaceRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/NamespaceServiceImpl.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/NamespaceRepositoryImplTest.java
Fix for https://github.com/opendatadiscovery/odd-platform/pull/451
> Disable namespace update with non-unique name

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AbstractCRUDRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AbstractSoftDeleteCRUDRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityTaskRunRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataSourceRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetFieldRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetVersionRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/EnumValueRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LabelRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/MetadataFieldRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/MetadataFieldValueRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/NamespaceRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/OwnerRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/RoleRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/TagRepositoryImpl.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/NamespaceRepositoryImplTest.java
fix for https://github.com/opendatadiscovery/odd-platform/issues/379
> Fill updated_at field when entity is updated

- odd-platform-ui/src/components/Alerts/Alerts.tsx
- odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx
> Fixed bug with alerts in "My objects" tab.

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImplTest.java
Closes https://github.com/opendatadiscovery/odd-platform/issues/400
> Add order by id to alerts and data entity

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/OwnershipRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/OwnershipRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/OwnerService.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/OwnerServiceImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/OwnershipServiceImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/RoleService.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/RoleServiceImpl.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/OwnershipServiceImplTest.java
> [Backend] - Ownership Refactoring. Initial commit

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/OwnershipRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/OwnershipRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/OwnershipServiceImpl.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/OwnerRepositoryImplTest.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/OwnershipRepositoryImplTest.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/RolesRepositoryImplTest.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/OwnershipServiceImplTest.java
Integration tests for Owner repo
> [Backend] - Owner Integration tests. Initial commit

- odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/CollectorForm.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/CollectorFormContainer.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/CollectorFormStyles.ts
- odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/NamespaceAutocomplete/NamespaceAutocomplete.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorForm/NamespaceAutocomplete/NamespaceAutocompleteContainer.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItem.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemContainer.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemStyles.ts
- odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemToken/CollectorItemToken.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemToken/CollectorItemTokenContainer.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemToken/CollectorItemTokenStyles.ts
- odd-platform-ui/src/components/Management/CollectorsList/CollectorSkeletonItem/CollectorSkeletonItem.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorsList.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorsListContainer.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorsListStyles.ts
- odd-platform-ui/src/components/Management/Management.tsx
- odd-platform-ui/src/redux/actions/collector.actions.ts
- odd-platform-ui/src/redux/actions/index.ts
- odd-platform-ui/src/redux/interfaces/collectors.ts
- odd-platform-ui/src/redux/interfaces/index.ts
- odd-platform-ui/src/redux/interfaces/state.ts
- odd-platform-ui/src/redux/reducers/collectors.reducer.ts
- odd-platform-ui/src/redux/reducers/index.ts
- odd-platform-ui/src/redux/selectors/collectors.selectors.ts
- odd-platform-ui/src/redux/thunks/collectors.thunks.ts
- odd-platform-ui/src/redux/thunks/index.ts
- CollectorsList, CollectorForm, CollectorItem, CollectorSkeletonItem
- interfaces, actions, thunks, reducer were created for CollectorsList component
Resolved #508 
> Collector frontend

- odd-platform-ui/.husky/prepare.sh
- odd-platform-ui/package.json
> Fix husky run on CI

- odd-platform-ui/.husky/prepare.sh
- odd-platform-ui/package.json
> Fix husky run locally in case when husky is not installed previously

- odd-platform-ui/src/components/shared/AppGraph/AppGraphLink/AppGraphLink.tsx
- odd-platform-ui/src/components/shared/AppGraph/AppGraphNode/AppGraphNode.tsx
Fixed bug with the disappearance of entities when pressing a loadMore button.
Fixed bug with lineage depth.
Resolve #530
> Fixed lineage bug.

- odd-platform-api/build.gradle
- odd-platform-api/gradle.properties
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/annotation/BlockingTransactional.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/annotation/ReactiveTransactional.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/DataSourceConfiguration.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/R2DBCConfiguration.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AbstractSoftDeleteCRUDRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/CollectorRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityTaskRunRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataSourceRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetFieldRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DatasetStructureRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/EnumValueRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/GroupEntityRelationRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LabelRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/LineageRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/NamespaceRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/OwnerRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/TagRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/UserOwnerMappingRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/JooqReactiveOperations.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataEntityServiceImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionServiceImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/OwnershipServiceImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/metadata/MetadataIngestionServiceImpl.java
- odd-platform-api/src/main/resources/application.yml
- odd-platform-api/src/test/resources/application-integration-test.yml
> Reactive jooq support

- odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetails.tsx
- odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItem.tsx
- odd-platform-ui/src/components/shared/AppButton/AppButtonStyles.ts
- odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItem.tsx
Fixed bug with app crash 
Resolve #558
> Fixed bug with token value equals null.

- .github/workflows/main.yaml
- .github/workflows/master.yaml
- .github/workflows/sonar-backend.yaml
- .github/workflows/sonar-frontend.yaml
- odd-platform-api/build.gradle
- odd-platform-ui/build.gradle
> Implement sonarcloud scans

- odd-platform-ui/src/components/shared/AppCheckbox/AppCheckbox.tsx
Fixed bug with "Pulling interval" checkbox in datasource form.
Resolve #579
> Fixed bug with checkbox.

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/AlertRepositoryImpl.java
> Fix recursive infinite loop in the Alerts API

- .github/CODEOWNERS
> Set up codeowners file

- odd-platform-api/src/main/resources/db/migration/V0_0_37__update_view_count.sql
> Fix view count field is not being updated

- odd-platform-ui/src/components/Terms/TermDetails/TermLinkedItemsList/LinkedItemsList.tsx
- odd-platform-ui/src/components/Terms/TermSearch/TermMainSearch/TermMainSearch.tsx
- odd-platform-ui/src/components/Terms/TermSearch/TermMainSearch/TermMainSearchContainer.tsx
- odd-platform-ui/src/lib/helpers.ts
- odd-platform-ui/src/redux/selectors/termSearch.selectors.ts
Fixed bug with search suggestions loader. 
Beautified values in entity class filter.
Resolve #634, resolve #632 on the frontend side.
> Fixed bug with search suggestions loader. 

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataQualityTestRelationRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataQualityTestRelationRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertLocatorImpl.java
> Link alert with dataset instead of data quality test

- .github/dependabot.yml
> Fix dependabot config typo

- odd-platform-api-contract/gradle.properties
- odd-platform-api/build.gradle
- odd-platform-api/gradle.properties
> Uplift R2DBC SPI

- .github/workflows/main-build.yaml
- .github/workflows/release-build.yaml
> Add concurrency to GH Actions jobs and workflows

- docker/injector/inject.py
- docker/injector/samples/ge_ingestion.json
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
- odd-platform-api/src/main/resources/db/migration/V0_0_43__additional_keys_to_dq_test_relation.sql
> Create hollow entities on DQT relation ingestion payload

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataEntityMapperImpl.java
- odd-platform-specification/components.yaml
- odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
- odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsContainer.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/Overview.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewContainer.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReport.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDataQualityReport/OverviewDataQualityReportContainer.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGroups/GroupItem/GroupItem.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewEntityGroupStats/OverviewEntityGroupStats.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewEntityGroupStats/OverviewEntityGroupStatsStyles.ts
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewTransformerStats/OverviewTransformerStats.tsx
- odd-platform-ui/src/components/shared/AppGraph/AppGraphCrossLink/AppGraphCrossLinkStyles.ts
- odd-platform-ui/src/components/shared/AppGraph/AppGraphLink/AppGraphLinkStyles.ts
- odd-platform-ui/src/redux/selectors/dataQualityTest.selectors.ts
Resolve #664
Resolve #719
Resolve #527
> Forbid to delete entity from datasource's deg

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/alert/AlertTypeEnum.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertLocator.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertLocatorImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/IngestionServiceImpl.java
- odd-platform-specification/components.yaml
Generate alerts for data transformer runs
> Alerts for data transformers

- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionServiceTest.java
Added test coverage for DataSourceIngestionService. Verified that it covers all (or at least most) of the logic in the service by commenting out parts of logic and running tests. 
> Test coverage for DataSourceIngestionService

- odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditForm.tsx
- odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateForm.tsx
- odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItem.tsx
- odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataValueEditor/MetadataValueEditor.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/OverviewDescription.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
- odd-platform-ui/src/components/DataEntityDetails/Ownership/OwnershipForm.tsx
- odd-platform-ui/src/components/Management/TagsList/TagCreateForm/TagCreateForm.tsx
- odd-platform-ui/src/components/Terms/TermDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
- odd-platform-ui/src/components/Terms/TermDetails/Ownership/OwnershipForm.tsx
- odd-platform-ui/src/components/Terms/TermSearch/TermForm/TermsForm.tsx
- odd-platform-ui/src/components/shared/AppButton/AppButton.tsx
- odd-platform-ui/src/components/shared/ConfirmationDialog/ConfirmationDialog.tsx
- odd-platform-ui/src/components/shared/DialogWrapper/DialogWrapper.tsx
DataEntity description saves on Enter.
Now forms are submitted by pressing Enter.
DataEntity description saves by pressing Shift+Enter.
If you want to move a line - press Enter.
Resolve #688
> Now forms submitting on Enter.

- odd-platform-ui/src/components/Management/TagsList/TagsList.tsx
- odd-platform-ui/src/redux/reducers/collectors.slice.ts
- odd-platform-ui/src/redux/reducers/datasources.slice.ts
- odd-platform-ui/src/redux/reducers/labels.slice.ts
- odd-platform-ui/src/redux/reducers/namespace.slice.ts
- odd-platform-ui/src/redux/reducers/tags.slice.ts
> Fix pagination in management section #808

- odd-platform-ui/src/redux/reducers/activity.slice.ts
> Fix activity order

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataQualityRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/sla/SLACalculator.java
- odd-platform-api/src/main/resources/db/migration/V0_0_50__rename_data_qa_severity.sql
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/sla/SLACalculatorTest.java
- odd-platform-specification/components.yaml
- odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
> Rename severity statuses

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLabelRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveTagRepositoryImpl.java
> Remove tags/labels which doesn't have any relations

- odd-platform-ui/src/components/Activity/Filters/Filters.tsx
> Incorrect update of counter on Activity page

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveAbstractCRUDRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveAbstractSoftDeleteCRUDRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveTagRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveTermRepositoryImpl.java
> Exclude non updatable fields from update many query

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetVersionRepositoryImpl.java
> Fix wrong dataset field enums count

- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewQualityTestStats/OverviewQualityTestStats.tsx
- odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
- odd-platform-ui/src/lib/constants.ts
> Tests overview ui fixes

- odd-platform-ui/src/lib/redux/helpers.ts
> assignWith update

- odd-platform-ui/package-lock.json
- odd-platform-ui/package.json
- odd-platform-ui/src/components/Activity/ActivityResults/ActivityResults.tsx
- odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
- odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsStyles.ts
- odd-platform-ui/src/components/DataEntityDetails/DataEntityGroupForm/DataEntityGroupForm.tsx
- odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditForm.tsx
- odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/LabelsAutocomplete/LabelsAutocomplete.tsx
- odd-platform-ui/src/components/DataEntityDetails/InternalNameFormDialog/InternalNameFormDialog.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewEntityGroupStats/OverviewEntityGroupStats.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTags/TagsEditForm/TagsEditFormAutocomplete/TagsEditFormAutocomplete.tsx
- odd-platform-ui/src/components/Terms/TermDetails/Overview/OverviewTags/TagsEditForm/TagsEditForm.tsx
- odd-platform-ui/src/components/shared/AppDateRangePicker/AppDateRangePicker.tsx
- odd-platform-ui/src/components/shared/AppDateRangePicker/AppDateRangePickerFooter/AppDateRangePickerFooter.tsx
- odd-platform-ui/src/components/shared/AppDateRangePicker/overrides.css
- odd-platform-ui/src/components/shared/AppMenuItem/AppMenuItemStyles.ts
- odd-platform-ui/src/components/shared/AppSelect/AppSelect.tsx
- odd-platform-ui/src/components/shared/Autocomplete/NamespaceAutocomplete/NamespaceAutocomplete.tsx
- odd-platform-ui/src/components/shared/Autocomplete/SearchSuggestionsAutocomplete/SearchSuggestionsAutocomplete.tsx
- odd-platform-ui/src/redux/selectors/dataentity.selectors.ts
- odd-platform-ui/src/redux/slices/dataEntityRuns.slice.ts
- odd-platform-ui/src/redux/thunks/dataentities.thunks.ts
Resolve #901
Resolve #869
Resolve #856
Resolve #831
> FE Bugfixes

- odd-platform-ui/package-lock.json
- odd-platform-ui/package.json
- odd-platform-ui/src/index.tsx
- odd-platform-ui/src/lib/redux/helpers.ts
Some packages updated to fix vulnerabilities.
> FE: Updating packages

- .github/workflows/main-build.yaml
- .github/workflows/release-build.yaml
- build.gradle
- odd-platform-api/build.gradle
> Add multiarch container build

- odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetStructureItem.tsx
> Fix primary/sort key labels

- .github/workflows/release-build.yaml
- .github/workflows/run-playwright-tests.yml
- .github/workflows/run-pr-tests.yaml
- tests/playwright.config.ts
**What changes did you make?** 
- Add GitHub Actions workflow file to run Playwright tests
- n/a
- сheck run results and artifacts
NOTES:
- Docs for Reusable Workflows in GitHub Actions: https://docs.github.com/en/actions/using-workflows/reusing-workflows
> Run Playwright tests in CI

- tests/features/owners/add-owner.spec.ts
- tests/features/tags/add-tag.spec.ts
- tests/features/tags/change-tag.spec.ts
- tests/features/tags/delete-tag.spec.ts
- tests/playwright.config.ts
- tests/ui/pages/index.ts
- tests/ui/pages/management/tags-page.ts
- tests/ui/pages/modals/add-tag-modal.ts
- tests/ui/pages/modals/delete-tag-modal.ts
- tests/ui/pages/modals/edit-tag-modal.ts
- tests/ui/pages/modals/index.ts
Added new tag's tests (create, change, delete), move spec of owners to folder 'owners' in features
> Playwright add tags tests

- gradle/libs.versions.toml
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/IngestionController.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataEntityService.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataEntityServiceImpl.java
> Implement fetch DEG Ingestion endpoint

- odd-platform-ui/package-lock.json
- odd-platform-ui/package.json
- odd-platform-ui/vite.config.ts
Updating FE packages with dependabot issues.
> Updating FE packages

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
> Count data entities without data source

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/DataEntityRepositoryImpl.java
> Don't modify updated_at field on view count increment

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/IngestionController.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionServiceImpl.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionServiceTest.java
> Do not propagate collector namespace to data sources while ingesting

- gradle/libs.versions.toml
- odd-platform-api/build.gradle
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/ODDPlatformConfiguration.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/housekeeping/HousekeepingJob.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/housekeeping/config/HousekeepingConfiguration.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/housekeeping/config/HousekeepingTTLProperties.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/FacetStateMapperImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/NotificationSubscriberStarter.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/SearchFacetRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveSearchFacetRepositoryImpl.java
- odd-platform-api/src/main/resources/application.yml
- odd-platform-api/src/main/resources/db/migration/V0_0_52__introduce_housekeeping.sql
- odd-platform-api/src/test/resources/application-integration-test.yml
> Introduce housekeeping for resolved alerts and outdated searches

- docker/injector/samples/bookshop_datalake_ingestion.json
- docker/injector/samples/s3_ingestion.json
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveAbstractCRUDRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/processor/DatasetStructureIngestionRequestProcessor.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/api/ingestion/DatasetIngestionTest.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/api/ingestion/utils/IngestionModelGenerator.java
> Fix several bugs in Ingestion API

- odd-platform-ui/src/components/shared/AppToolbar/AppToolbar.tsx
- odd-platform-ui/src/components/shared/AppToolbar/AppToolbarStyles.ts
> Owner name displayed firstly in toolbar.

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/AlertLocatorImpl.java
> Filter entities without penultimate versions in AlertLocator

- odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItem.tsx
Fixed bug with metadata creating
> Metadata bugfix

- odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateForm.tsx
- odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataCreateForm/MetadataCreateFormItem/MetadataCreateFormItem.tsx
- odd-platform-ui/src/components/DataEntityDetails/Metadata/MetadataValueEditor/MetadataValueEditor.tsx
Resolved bug with creating metadata form
> Creating metadata bugfix

- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/OverviewDescription.tsx
Markdown switched to light mode.
> Markdown switched to light mode.

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/ODDPlatformConfiguration.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/SchedulingConfiguration.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/SessionConfiguration.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/leaderelection/PostgreSQLLeaderElectionManager.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/leaderelection/PostgreSQLLeaderElectionManagerImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/activity/ActivityPartitionCreationJob.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/activity/ActivityServiceImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/activity/ActivityTablePartitionManager.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/activity/ActivityTablePartitionManagerImpl.java
- odd-platform-api/src/main/resources/application.yml
> Fix deadlock on activity partition creation

- odd-platform-api/src/main/resources/application.yml
> Set infinite session

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/datacollaboration/config/DataCollaborationProperties.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/datacollaboration/job/DataCollaborationMessageSenderJob.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/datacollaboration/repository/DataCollaborationRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/datacollaboration/repository/DataCollaborationRepositoryImpl.java
- odd-platform-api/src/main/resources/application.yml
- odd-platform-api/src/main/resources/db/migration/V0_0_63__add_try_count_to_message.sql
> Retry sending messages to MessageProviders

- .gitignore
- tests/features/filters/filters.spec.ts
- tests/features/search/search.spec.ts
- tests/features/search/search_in_data_entity.spec.ts
- tests/features/tags/add-tag.spec.ts
- tests/features/tags/change-tag.spec.ts
- tests/package.json
- tests/playwright.config.ts
- tests/ui/elements/custom-element.ts
- tests/ui/elements/list.ts
- tests/ui/pages/catalog/catalog-page.ts
- tests/ui/pages/data_entity/overview.page.ts
- tests/ui/pages/management/tags-page.ts
- tests/ui/pages/modals/add-tag-modal.ts
> DEBUG | resolve conflicts 

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/DataEntityController.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLineageRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLineageRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/LineageService.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/LineageServiceImpl.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/service/LineageServiceTest.java
- odd-platform-specification/openapi.yaml
- odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsTabs/DataEntityDetailsTabs.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/Lineage.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageControls/LineageControls.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/LineageGraph.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/Info/GroupedEntitiesListModal/GroupedEntitiesListModal.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/Info/Info.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/LoadMoreButton/LoadMoreButton.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/Node.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/NodeTitle/NodeTitle.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/ZoomableLineage.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/lineageLib/LineageContext/LineageContext.ts
- odd-platform-ui/src/components/DataEntityDetails/Lineage/lineageLib/LineageContext/LineageProvider.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/lineageLib/constants.ts
- odd-platform-ui/src/components/DataEntityDetails/Lineage/lineageLib/generateNodeSize.ts
- odd-platform-ui/src/components/DataEntityDetails/Lineage/lineageLib/interfaces.ts
- odd-platform-ui/src/lib/hooks/index.ts
- odd-platform-ui/src/lib/hooks/useAppPaths.ts
- odd-platform-ui/src/lib/hooks/useQueryParams.ts
- odd-platform-ui/src/redux/interfaces/dataentityLineage.ts
- odd-platform-ui/src/redux/slices/dataEntityLineage/dataEntityLineage.slice.ts
- odd-platform-ui/src/redux/thunks/dataentityLineage.thunks.ts
> Lineage state in query params

- odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/NotificationSettings/AlertTypeRange/AlertTypeRange.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/Lineage.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/LineageGraph.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/Classes/Classes.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/HiddenDependencies/HiddenDependencies.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/Info/Info.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/Node.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/LineageGraph/Node/NodeTitle/NodeTitle.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/ZoomableLineage/ZoomableLineage.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/lineageLib/constants.ts
- odd-platform-ui/src/lib/hooks/useQueryParams.ts
- odd-platform-ui/src/redux/selectors/dataentityLineage.selectors.ts
Lineage "Main" now work as expected
> Bugfix: Lineage button "Main" work incorrectly

- .github/workflows/run-pr-tests.yaml
- tests/README.md
- Do not trigger tests after updating PR's title or description.
- Add ability to trigger test without creating PR (feature branch name should start or end with `branch`)
- n/a
- n/a
> Worflow triggering rules

- README.md
> Fixed badges

- README.md
Updated README.md integration list
> Update integrations list

- tests/playwright.config.ts
**What changes did you make?** 
- bump timeout (to make tests more stable)
- n/a
- n/a
> Playwright | bump timeout

- CONTRIBUTING.md
Added github contribution workflow 
Would be nice if anybody else would run the flow
I've run the guideline locally
> Updated Contribution page with github workflow

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/metric/InternalIngestionMetricsServiceImpl.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/api/ingestion/MetricsIngestionTest.java
- odd-platform-api/src/test/resources/metrics/gauge_and_count.json
- odd-platform-api/src/test/resources/metrics/histogram_and_summary.json
> Metrics bugfix + test enhancement

- .github/workflows/sonar-frontend.yaml
- odd-platform-ui/package-lock.json
- odd-platform-ui/package.json
- odd-platform-ui/src/components/shared/BooleanFormatted/BooleanFormatted.tsx
- odd-platform-ui/src/components/shared/BooleanFormatted/__tests__/BooleanFormatted.test.tsx
- odd-platform-ui/src/components/shared/EntityClassItem/__tests__/EntityClassItem.test.tsx
- odd-platform-ui/src/components/shared/NumberFormatted/NumberFormatted.tsx
- odd-platform-ui/src/components/shared/NumberFormatted/__tests__/NumberFormatted.test.tsx
- odd-platform-ui/src/lib/hooks/useQueryParams.ts
- odd-platform-ui/src/lib/testHelpers.tsx
- odd-platform-ui/src/setupTests.ts
- odd-platform-ui/vite.config.ts
> New FE test environment

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/dto/ingestion/HashableDatasetField.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/ingestion/IngestionMapperImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetVersionRepository.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDatasetVersionRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DatasetStructureServiceImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/DatasetVersionHashCalculator.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/ingestion/processor/DatasetStructureIngestionRequestProcessor.java
- odd-platform-api/src/main/resources/db/migration/V0_0_68__clear_dataset_version_hash.sql
> Recalculate dataset structure hash

- docker/config/injector/datasources/datasources.json
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/DataSourceMapper.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/ingestion/DataSourceIngestionMapperImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveSearchEntrypointRepositoryImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/util/FTSConstants.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataSourceIngestionServiceImpl.java
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/DataSourceServiceImpl.java
- odd-platform-api/src/main/resources/db/migration/V0_0_71__datasource_refactor.sql
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/BaseIngestionTest.java
- odd-platform-api/src/test/java/org/opendatadiscovery/oddplatform/repository/DataSourceRepositoryImplTest.java
- odd-platform-api/src/test/resources/ingestion/datasource/datasources.json
- odd-platform-specification/components.yaml
- odd-platform-ui/src/components/Management/DataSourcesList/DataSourceForm/DataSourceForm.tsx
- odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItem.tsx
- odd-platform-ui/src/redux/selectors/datasetStructure.selectors.ts
- tests/docker/injector/datasources/datasources.json
> Refactor datasources

- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGeneral/OverviewGeneral.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewQualityTestStats/OverviewQualityTestStats.tsx
- odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetails.tsx
- odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
- odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverviewStyles.ts
- odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItem.tsx
- odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportItem/TestReportItemStyles.ts
- odd-platform-ui/src/components/shared/elements/AppTabs/AppTabs.tsx
- odd-platform-ui/src/components/shared/elements/TestRunStatusItem/TestRunStatusItemStyles.ts
- odd-platform-ui/src/components/shared/elements/TestRunStatusReasonModal/TestRunStatusReasonModal.tsx
- odd-platform-ui/src/components/shared/elements/index.ts
> DQ test status reason displaying

- odd-platform-ui/src/components/DataEntityDetails/DataCollaboration/MessagesList/Message/Message.tsx
- odd-platform-ui/src/components/DataEntityDetails/DataCollaboration/MessagesList/Message/MessageStatus/MessageStatus.styles.ts
- odd-platform-ui/src/components/DataEntityDetails/DataCollaboration/MessagesList/Message/MessageStatus/MessageStatus.tsx
- odd-platform-ui/src/components/DataEntityDetails/DataCollaboration/MessagesList/MessagesList.tsx
- odd-platform-ui/src/theme/interfaces.ts
- odd-platform-ui/src/theme/palette.ts
> Discussions message status.

- odd-platform-ui/pnpm-lock.yaml
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewMetadata/OverviewMetadata.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItem.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemStyles.ts
- odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItemToken/CollectorItemToken.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorSkeletonItem/CollectorSkeletonItem.tsx
- odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItem.tsx
- odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItemStyles.ts
- odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItemToken/DataSourceItemToken.tsx
- odd-platform-ui/src/components/Management/DataSourcesList/DataSourceSkeletonItem/DataSourceSkeletonItem.tsx
- odd-platform-ui/src/components/Terms/TermDetails/Overview/Overview.tsx
- odd-platform-ui/src/components/Terms/TermDetails/Overview/OverviewStyles.ts
- odd-platform-ui/src/components/Terms/TermSearch/TermForm/TermsForm.tsx
- odd-platform-ui/src/components/shared/elements/AppDatePicker/AppDatePicker.tsx
- odd-platform-ui/src/components/shared/elements/AppInput/AppInput.tsx
- odd-platform-ui/src/components/shared/elements/AppTabs/AppTab/AppLinkTab.tsx
- odd-platform-ui/src/components/shared/elements/AppTabs/AppTabs.tsx
- odd-platform-ui/src/components/shared/elements/InfoItem/InfoItem.tsx
- odd-platform-ui/src/redux/slices/terms.slice.ts
- odd-platform-ui/src/theme/typography.ts
> Term markdown

- odd-platform-ui/src/locales/i18n.ts
> Locales fix.

- gradle/libs.versions.toml
- odd-platform-api/build.gradle
- odd-platform-api/src/main/resources/application.yml
close https://github.com/opendatadiscovery/odd-platform/issues/1446
> 1446 - Created Swagger UI for OpenAPI Specifications

- odd-platform-ui/package.json
- odd-platform-ui/pnpm-lock.yaml
- odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItem.tsx
- odd-platform-ui/src/components/App.tsx
- odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsRoutes/DataEntityDetailsRoutes.tsx
- odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetStructureHeader/DatasetStructureHeader.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/HierarchyLineage/ZoomableLineage/LineageGraph/Node/Info/InfoStyles.ts
- odd-platform-ui/src/components/DataEntityDetails/Lineage/HierarchyLineage/ZoomableLineage/LineageGraph/Node/Node.tsx
- odd-platform-ui/src/components/DataEntityDetails/Lineage/HierarchyLineage/ZoomableLineage/LineageGraph/Node/NodeTitle/NodeTitle.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewStats.tsx
- odd-platform-ui/src/components/shared/elements/Activity/ActivityFilterItems/SingleFilter/SingleFilter.tsx
- odd-platform-ui/src/components/shared/elements/AppSelect/AppSelect.tsx
- odd-platform-ui/src/components/shared/elements/AppToolbar/AppToolbar.tsx
- odd-platform-ui/src/components/shared/elements/DatasourceLogo/DatasourceLogo.tsx
- odd-platform-ui/src/components/shared/elements/TagItem/TagItem.tsx
- odd-platform-ui/src/lib/hooks/api/dataEntity.ts
- odd-platform-ui/src/redux/store/index.ts
- tests/features/filters/filters.spec.ts
- tests/ui/pages/catalog/catalog.page.ts
- Resolve serialization console errors.
- Add data source logo into linage. Resolves https://github.com/opendatadiscovery/odd-platform/issues/1356
- Update react router
- Cleanup some html dom violations
> chore: Resolve serialization console errors. Add data source logo into linage.

- odd-platform-ui/src/components/App.tsx
- odd-platform-ui/src/components/Overview/Overview.tsx
- odd-platform-ui/src/components/Overview/TopTagsList/TopTagsList.tsx
- odd-platform-ui/src/components/Terms/TermDetails/TermLinkedColumnsList/LinkedColumnsList.tsx
- odd-platform-ui/src/index.tsx
- odd-platform-ui/src/lib/hooks/api/appInfo.ts
- odd-platform-ui/src/lib/hooks/api/dataEntity.ts
- odd-platform-ui/src/lib/hooks/api/dataEntityAttachments/dataEntityFiles.ts
- odd-platform-ui/src/lib/hooks/api/datasetApi/datasetApi.ts
- odd-platform-ui/src/lib/hooks/api/datasetField.ts
- odd-platform-ui/src/lib/hooks/api/directory.ts
- odd-platform-ui/src/lib/hooks/api/tags.ts
- odd-platform-ui/src/lib/hooks/api/terms.ts
- odd-platform-ui/src/redux/selectors/mainContentLoader.selectors.ts
- odd-platform-ui/src/redux/selectors/profile.selectors.ts
> chore: proper tags fetching on main overview page. Prepare useQuery hooks to upgrade to 5v

- .github/workflows/cve.yaml
Implemented monthly CVE checks workflow. Could be also run manually.
Tested on a fork, logs example [here](https://github.com/Haarolean/odd-platform/actions/runs/6656410909/job/18088884201)
> Infra: Implement monthly CVE checks workflow

- SECURITY.md
Added security policy file to satisfy github security advisories
> Infra: Implement security policy

- tests/docker/docker-compose.yaml
> chore: update docker-compose for tests

- gradle/libs.versions.toml
- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/config/SwaggerUIConfiguration.java
> 1518 - Splitted Swagger UI into 2 pages for platform-api and ingestion-api

- odd-platform-ui/src/components/App.tsx
- odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsRoutes/DataEntityDetailsRoutes.tsx
- odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsTabs/DataEntityDetailsTabs.tsx
- odd-platform-ui/src/components/DataEntityDetails/DataEntityQueryExamples/DataEntityDetailsQueryExamples.tsx
- odd-platform-ui/src/components/DataModelling/DataModellingRoutes.tsx
- odd-platform-ui/src/components/DataModelling/QueryExamplesContainer.tsx
- odd-platform-ui/src/components/shared/elements/QueryExamples/QueryExamplesListHeader.tsx
- odd-platform-ui/src/components/shared/elements/QueryExamples/QueryExamplesListItem.tsx
- odd-platform-ui/src/components/shared/icons/PreviewIcon.tsx
- odd-platform-ui/src/components/shared/icons/UnlinkIcon.tsx
- odd-platform-ui/src/components/shared/icons/index.ts
- odd-platform-ui/src/lib/hooks/api/dataModelling/queryExamples.ts
- odd-platform-ui/src/lib/hooks/useAppPaths/useAppPaths.ts
- odd-platform-ui/src/routes/dataEntitiesRoutes.ts
- odd-platform-ui/src/routes/dataModellingRoutes.ts
Unassign query example from dataset.
Wrap action button into permissions provider
Fix data entity details tabs
> feature(fe): Unassign query example from dataset.

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReferenceDataRepositoryImpl.java
- odd-platform-specification/components.yaml
- odd-platform-ui/src/components/DataEntityDetails/DatasetData/DatasetDataTable/DatasetDataTableRowCell.tsx
- odd-platform-ui/src/components/DataEntityDetails/DatasetData/DatasetDataTable/DatasetDataTableRowCell/DatasetDataTableRowCellDate.tsx
- odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructure.tsx
- odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetFieldOverview/DatasetFieldHeader/DatasetFieldHeader.tsx
- odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetStructureList/DatasetStructureList.tsx
- odd-platform-ui/src/components/shared/elements/forms/ColumnForm.tsx
related to https://github.com/opendatadiscovery/odd-platform/pull/1574
> Bugfix: date cells, lookup table definition permissions, boolean cells

- odd-platform-ui/src/components/Search/Results/Results.tsx
- odd-platform-ui/src/redux/selectors/dataentitySearch.selectors.ts
resolves https://github.com/opendatadiscovery/odd-platform/issues/1474
> bugfix(fe): Search page freezing on loading state for tabs with 0 entities

- odd-platform-ui/package.json
- odd-platform-ui/pnpm-lock.yaml
- odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetFieldOverview/DatasetFieldDescription/DatasetFieldDescription.tsx
- odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetFieldOverview/DatasetFieldDescription/DatasetFieldDescriptionPreview/DatasetFieldDescriptionPreview.tsx
- odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetFieldOverview/DatasetFieldTerms/TermItem/TermItem.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewDescription/InternalDescription/InternalDescriptionPreview/InternalDescriptionPreview.tsx
- odd-platform-ui/src/components/Management/CollectorsList/CollectorItem/CollectorItem.tsx
- odd-platform-ui/src/components/Management/DataSourcesList/DataSourceItem/DataSourceItem.tsx
- odd-platform-ui/src/components/shared/elements/CollapsibleInfoContainer/CollapsibleInfoContainer.styles.ts
- odd-platform-ui/src/components/shared/elements/InfoItem/InfoItem.tsx
- odd-platform-ui/src/components/shared/elements/Markdown/Markdown.tsx
> bugfix:  markdown is rendered correctly on dataset field overview page

- .github/workflows/main-build.yaml
> change workflow to use new dev env

- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewRelationshipStats/OverviewRelationshipStats.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewRelationshipStats/OverviewRelationshipStatsStyles.ts
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewRelationshipStats/OverviewRelationshipType/OverviewEntityRelationship.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewRelationshipStats/OverviewRelationshipType/OverviewGraphRelationship.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewRelationshipStats/RelationshipIcon.tsx
- odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewStats.tsx
- odd-platform-ui/src/components/DataModelling/Relationships/RelationshipsListItem.tsx
- odd-platform-ui/src/components/Overview/DataEntitiesUsageInfo/DataEntitiesUsageInfo.tsx
- odd-platform-ui/src/components/Search/Results/Results.styles.ts
- odd-platform-ui/src/components/Search/Results/SearchResultsTabs/SearchResultsTabs.tsx
- odd-platform-ui/src/components/shared/elements/Relationships/RelationshipDatasetInfo.tsx
- odd-platform-ui/src/lib/hooks/api/dataModelling/relatioships.ts
- odd-platform-ui/src/redux/selectors/dataentity.selectors.ts
> 1640 Relationships details overview

- odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/lib/useStructure.ts
> use business name for search columns on dataset strucuture page

- odd-platform-ui/src/components/Terms/TermDetails/Overview/Overview.tsx
> 1688 - tags should be shown on the Terms page

- README.md
Lint the README and update the broken collector URLs to point to the new repo.
Also add missing connectors to the table.
N/A
N/A
> docs: lint and update collectors

- odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveDataEntityRepositoryImpl.java
> 1705 - sort the default catalog view firstly based on status in the following sequence:STABLE, DEPRECIATED,DRAFT,UNASSIGNED,DELETED

- odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/lib/useStructure.ts
This is the  MR #1708. I have enhanced the search by returning all the occurrences. Please feel free to provide any feedback on the approaches/ implementation strategy. 
Current Search
> Enchancing the Structure search

- .github/workflows/run-playwright-tests.yml
Update of actions/upload-artifact: v3 to v4
> Fix of upload-artifact from deprecated v3 to v4.
