.github/release-drafter.yaml
.github/workflows/release-build.yaml
.github/workflows/release-drafter.yaml
odd-platform-api/build.gradle

- add the ability to define project version as Gradle command-line option
- add release drafter to sync draft release with pushes in developing period
- add base release pipeline 
The strategies of release:
- Regular release: after completing required milestones we switch GH release from draft state to published, this action will trigger release build pipeline
- Custom version: need to trigger manually release build action and specify the branch to build and version
The version is incremented automatically after GH release is published, all snapshot builds after release be builder as `<next-release-version>-<commit-sha>`

CI actions for build and release

---

odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx
odd-platform-ui/src/components/DataEntityDetails/DataEntityDetailsContainer.tsx
odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewQualityTestStats/OverviewQualityTestStats.tsx
odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewQualityTestStats/OverviewQualityTestStatsStyles.ts
odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewStats.tsx
odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStyles.ts
odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunItem/QualityTestRunItem.tsx
odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunItem/QualityTestRunItemStyles.ts
odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunsHistory.tsx
odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunsHistoryContainer.tsx
odd-platform-ui/src/components/DataEntityDetails/QualityTestRunsHistory/QualityTestRunsHistoryStyles.ts
odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReport.tsx
odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsHistory/TestReportDetailsHistory.tsx
odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
odd-platform-ui/src/components/shared/TestRunStatusItem/TestRunStatusItem.tsx
odd-platform-ui/src/lib/paths.ts
odd-platform-ui/src/redux/selectors/dataentity.selectors.ts

Added latest test run info to the overview of Quality Test page.
Added History page with test runs info.

Data quality test details: info about last run and expectations and test runs history page

---

odd-platform-ui/src/components/DataEntityDetails/DataEntityDetails.tsx

Bug fixed.
Removed 'Lineage' tab from data quality entity page.

Bug fix: DataEntity tabs move to the page of the previous entity

---

odd-platform-ui/src/components/Alerts/AlertsList/AlertItem/AlertItem.tsx
odd-platform-ui/src/components/DataEntityDetails/DataEntityAlerts/DataEntityAlertItem/DataEntityAlertItem.tsx
odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureItem/DatasetStructureItem.tsx
odd-platform-ui/src/components/DataEntityDetails/TestReport/TestReportDetails/TestReportDetailsOverview/TestReportDetailsOverview.tsx
odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemContainer.tsx
odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreview.tsx
odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreviewContainer.tsx
odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemPreview/ResultItemPreviewStyles.ts
odd-platform-ui/src/components/Search/Results/ResultItem/ResultItemStyles.ts
odd-platform-ui/src/components/Search/Results/Results.tsx
odd-platform-ui/src/components/Search/Results/ResultsContainer.tsx
odd-platform-ui/src/components/Search/Results/ResultsStyles.ts
odd-platform-ui/src/components/shared/AppTooltip/AppTooltip.tsx
odd-platform-ui/src/components/shared/AppTooltip/AppTooltipStyles.ts
odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItem.tsx
odd-platform-ui/src/components/shared/LabeledInfoItem/LabeledInfoItemStyles.ts
odd-platform-ui/src/lib/constants.ts
odd-platform-ui/src/redux/interfaces/datasetStructure.ts
odd-platform-ui/src/theme/palette.ts

- Implemented data entity preview on search page.
- Refactored ResultsList and ResultItem components to styled.

Feature: Data Entity card preview on the search page

---

.github/workflows/build.yaml
.github/workflows/codestyle.yaml
.github/workflows/release-build.yaml

Remove NODE_ENV environment variable from CI processes, because development dependencies are not being installed during build part of CI process.

CI env updates

---

odd-platform-ui/src/components/Search/Results/ResultItem/ResultItem.tsx
odd-platform-ui/src/components/Search/Results/Results.tsx
odd-platform-ui/src/components/Search/Results/ResultsStyles.ts
odd-platform-ui/src/lib/hooks.ts

Deleted paddings for an inner container that displays the name(paddings appear twice because the outer container has them too). Added empty container with scrollbar width to the header of the table on the search page.
The problem is scrollbar is taking width out of the container. But if the scrollbar is absent, it will break styles once again. I tried to use clientHeight и scrollHeight properties, but because we use the infinite scroll component, it doesn't work as expected. Heights will be equal at the start and change only after downloading new data using pagination, so I cannot find when the scrollbar appears. That's why I changed styles, so that scrollbar appears always.
**How Has This Been …

fixed search page styles

---

odd-platform-ui/src/components/DataEntityDetails/DataEntityGroupForm/DataEntityGroupForm.tsx
odd-platform-ui/src/components/DataEntityDetails/DataEntityGroupForm/EntityItem/EntityItem.tsx
odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewGroups/AddDataEntityToGroupForm/AddDataEntityToGroupForm.tsx
odd-platform-ui/src/components/shared/Autocomplete/SearchSuggestionsAutocomplete/SearchSuggestionsAutocomplete.tsx

Data entity group form bug #779

---

odd-platform-ui/src/components/Activity/ActivityResults/ActivityItem/ActivityItem.tsx
odd-platform-ui/src/components/DataEntityDetails/DataEntityActivity/ActivityResults/ActivityItem/ActivityItem.tsx
odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditForm.tsx
odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureTable/DatasetStructureList/DatasetStructureItem/DatasetFieldInfoEditForm/DatasetFieldInfoEditFormStyles.ts
odd-platform-ui/src/components/shared/Activity/ActivityFields/EnumsActivityField/EnumsActivityField.tsx
odd-platform-ui/src/components/shared/Activity/ActivityFields/StringActivityField/StringActivityField.tsx
odd-platform-ui/src/components/shared/AppPopover/AppPopover.tsx
odd-platform-ui/src/components/shared/AppPopover/AppPopoverStyles.ts
odd-platform-ui/src/components/shared/TruncatedLabel/TruncatedLabel.tsx
odd-platform-ui/src/redux/reducers/activity.slice.ts

Activity bug fixes.

---

docker/README.md

1. fix typos
1. fix formatting in the "Assumptions" section.
The following text should apply to both "Linux/Mac" and "Windows Powershell":
```Replace <PORT_NUMBER> with 5432 and 8080. Empty output means that the port is free and ready to go.```
- Compare the "Assumptions" section in README:
- before fix: https://github.com/opendatadiscovery/odd-platform/blob/41b344bb/docker/README.md#assumptions
- after fix: https://github.com/opendatadiscovery/odd-platform/blob/d7ddc340/docker/README.md#assumptions
- n/a

README: fix formatting

---

odd-platform-ui/build.gradle

Extend `gradle clean` task with deleting generated API models for UI

---

.github/workflows/main-build.yaml
.github/workflows/release-build.yaml
.github/workflows/run-playwright-tests.yml
.github/workflows/run-pr-tests.yaml
.github/workflows/sonar-backend.yaml
.github/workflows/sonar-frontend.yaml

- Update workflows with the latest versions of actions that run on Node 16  (to fix deprecation warnings in GitHub Actions).
More info: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
1. Please keep in mind that I was able to verify my changes only in the following files:
- `.github/workflows/run-playwright-tests.yml`
- `.github/workflows/run-pr-tests.yaml`
because those workflows were triggered for this PR.
1. Changes in the following files are NOT tested (because I'm not sure how to trigger them): 
- `.github/workflows/main-build.yaml`
- `.github/workflows/release-build.yaml`
- `.github/workflows/sonar-backend.yaml` …

Update workflows with latest versions of actions which runs on Node 16

---

.github/workflows/run-playwright-tests.yml
tests/features/owners/add-owner.spec.ts
tests/package.json

- Run prettier in CI to check formatting issues 
- n/a
- check the `format:check` job in GitHub Actions.
- the job will pass if the code has no formatting issues  
(See example: https://ibb.co/RjYvHXm)
- the job will fail with an error if the code has formatting issues 
(See example: https://ibb.co/4f4zZcC)
NOTE: 
- Command for fixing formatting issues (`npm run format`) already mentioned in the [tests/README.md](https://github.com/opendatadiscovery/odd-platform/blob/2a6b870/tests/README.md#useful-commands).

Check formatting in CI

---

tests/features/activity/activity.spec.ts
tests/features/search/search_in_data_entity.spec.ts
tests/playwright.config.ts

- Fixed concurrent modification error in the test (by creating an owner for another data entity)
- Parallelized tests: 4 workers used
- The time to run the test suite in CI should decrease several times

Fix concurrent modification error in tests and run tests in parallel (4 threads)

---

tests/playwright.config.ts

- Enable the built-in `github` reporter to get automatic failure annotations when running tests in GitHub actions.
- Documentation: https://playwright.dev/docs/test-reporters#github-actions-annotations
- Annotations displayed in multiple places:
1. in the code during the PR review
(See example commit: https://github.com/opendatadiscovery/odd-platform/commit/aa0db995; See [screenshot](https://ibb.co/4sMZFr7))
2. in the "Summary" section of the run in GitHub Actions
(See [link](https://github.com/opendatadiscovery/odd-platform/actions/runs/3890550202); See [screenshot](https://ibb.co/gmFDDNt))

Playwright | Enable the "github" reporter to get automatic failure annotations in GitHub actions

---

odd-platform-ui/pnpm-lock.yaml
odd-platform-ui/src/components/Management/PolicyList/PolicyItem/PolicyItem.tsx
odd-platform-ui/src/components/Management/RolesList/RoleItem/RoleItem.tsx

There were a few minor markup collisions
**Before:**
**After:**

chore: minor css fixes for roles and polices managment page

---

odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetFieldOverview/DatasetFieldTerms/TermItem/TermItem.tsx
odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewTerms/TermItem/TermItem.tsx
odd-platform-ui/src/components/shared/elements/forms/AssignTermForm/AssignTermForm.tsx
odd-platform-ui/src/lib/hooks/api/terms.ts

correct rendering terms' markdown on dataset structure page. resolves https://github.com/opendatadiscovery/odd-platform/issues/1464

(bugfix): correct rendering terms' markdown on dataset structure page

---

odd-platform-ui/package.json
odd-platform-ui/pnpm-lock.yaml
odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureCompare/DatasetStructureCompare.tsx
odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetFieldOverview/DatasetFieldHeader/DatasetFieldInternalNameForm/DatasetFieldInternalNameForm.tsx
odd-platform-ui/src/components/DataEntityDetails/DatasetStructure/DatasetStructureOverview/DatasetStructureView/DatasetFieldOverview/DatasetFieldTerms/AssignFieldTermForm/AssignFieldTermForm.tsx
odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewAttachments/EditLinkForm/EditLinkForm.tsx
odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewAttachments/SaveFilesForm/SaveFilesForm.tsx
odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewAttachments/SaveLinksForm/SaveLinksForm.tsx
odd-platform-ui/src/components/DataEntityDetails/Overview/OverviewStats/OverviewEntityGroupItems/OverviewEntityGroupItems.tsx
odd-platform-ui/src/components/Directory/DataSourceList/DataSourceList.tsx
odd-platform-ui/src/components/Directory/Directory/Directory.tsx
odd-platform-ui/src/components/Directory/Entities/Entities.tsx
odd-platform-ui/src/components/Directory/Entities/EntitiesList/EntitiesList.tsx
odd-platform-ui/src/components/Management/Integrations/IntegrationPreviewList/IntegrationPreviewList.tsx
odd-platform-ui/src/components/shared/elements/AppErrorPage/AppErrorPage.tsx
odd-platform-ui/src/components/shared/elements/EntityStatus/StatusSettingsForm/StatusSettingsForm.tsx
odd-platform-ui/src/index.tsx
odd-platform-ui/src/lib/hooks/api/dataEntity.ts
odd-platform-ui/src/lib/hooks/api/dataEntityAttachments/dataEntityFiles.ts
odd-platform-ui/src/lib/hooks/api/dataEntityAttachments/dataEntityLinks.ts
odd-platform-ui/src/lib/hooks/api/datasetField.ts
odd-platform-ui/src/lib/hooks/api/directory.ts
odd-platform-ui/src/lib/hooks/api/integration.ts
odd-platform-ui/src/lib/hooks/api/terms.ts
odd-platform-ui/src/lib/interfaces/shared.ts
odd-platform-ui/src/redux/lib/handleResponseThunk.ts

_Why do we need this?_
We are going to reduce redux usage across app especially in places where common storage doesn't make sense and produces a lot of boilerplate code. For that purpose we have to keep libraries that will take a place in data fetching and management on FE.

Dependencies: upgrade react-query from 4 to 5

---

odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/config/NotificationConfiguration.java
odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/notification/sender/EmailNotificationSender.java

Use odd.platform-base-url property instead of PLATFORM_HOST_URL environment variable for email notifications.

1497 - Use odd.platform-base-url property instead of PLATFORM_HOST_URL

---

README.md

The only branch with the role "main" should be at https://github.com/opendatadiscovery/charts

Fix Readme: change reference from master to main branch for odd charts

---

odd-platform-ui/README.md
odd-platform-ui/generate.sh
odd-platform-ui/package.json

1. fixed command to generate api to work on windows and unix
2. removed only-allow pnpm because it doesn't work https://github.com/pnpm/only-allow/issues/27
3. updated readme
run pnpm build on windows

fix(odd-platform-ui): fix ui build for windows

---

odd-platform-ui/src/redux/thunks/policy.thunks.ts

this is openapi codegen weird behaviour. According openapi spec it must returns string but in reality it returns json parsed object.

hotfix: fetch policy schema

---

odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/controller/AppInfoController.java
odd-platform-specification/components.yaml
odd-platform-ui/src/components/Overview/Overview.tsx
odd-platform-ui/src/components/shared/elements/AppToolbar/AppInfoMenu/AppInfoMenu.tsx
odd-platform-ui/src/lib/hooks/api/appInfo.ts

This pull request fixes the issue where a user receives a 500 Internal Server Error for owner association requests when trying to "Sync your account with existing owner" with no authentication method configured. The functionality is now disabled if no authentication method is provided in the config.
authType: DISABLED
authType: other options
Fixes #1380

Hide "Sync your account with existing owner" with no authentication method configured

---

gradle/libs.versions.toml
odd-platform-api/src/main/resources/bootstrap.yml

By default, AWS Parameters Store is disabled. 
In case, user want to enable it, need to specify:
- AWS_PARAMSTORE_ENABLED=true (for default values)
- AWS_SECRETSMANAGER_ENABLED=true (for Secured values)
Note : this naming is [hardcoded](https://docs.spring.io/spring-cloud-aws/docs/2.2.3.RELEASE/reference/html/appendix.html)
In case, you want to enable this on your local env, you should also specify:
- AWS_ACCESS_KEY_ID
- AWS_REGION
- AWS_SECRET_KEY
([How to setup this variables for local env](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/signup-create-iam-user.html))
By default, 
aws.paramstore.prefix = /odd
aws.paramstore.name = platform_config
In result, platform will get variables which have naming like: /odd/platform_config/[variable.name]
IMPORTANT
As name separator for …

1608 - added support of AWS Parameters Store

---

odd-platform-ui/src/components/DataEntityDetails/Overview/Overview.tsx

This is the MR [#1692 ](https://github.com/opendatadiscovery/odd-platform/issues/1692) for the issue which we raised. Swapped the About/Description section for the data-entities with the Metadata, kept the Attachment in the middle.

User Interface: Moving 'About/Description' Section to the Top in ODD #1692

---

odd-platform-ui/src/components/Terms/TermSearch/TermForm/TermsForm.tsx

This is the MR [#1700 ](https://github.com/opendatadiscovery/odd-platform/issues/1700). So whenever we edit the terms, it does not throw errors. The Rest of the functionality is the same. Please review the code and let me know if there are any issues. I'm happy to resolve them. I'm attaching the screenshot for reference.

Editing the terms shouldn't throw alerts. 
